# Generated by Django 5.0.4 on 2024-04-09 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnfc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('payment', 'Payment'), ('credit', 'Credit')], max_length=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
