# Generated by Django 5.0.4 on 2024-04-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnfc', '0002_transaction_transaction_type_wallet_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
