# Generated by Django 5.0.4 on 2024-04-11 13:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartnfc', '0005_alter_paynowpayment_browser_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('trans_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('amount_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('currency', models.CharField(blank=True, max_length=50)),
                ('receiver', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='smartnfc.wallet')),
            ],
        ),
    ]
